include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    # generated code
    - lib/generated_plugin_registrant.dart
    - build/**
    - flutter/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"

linter:
  rules:
    prefer_single_quotes: true
    always_specify_types: true
